---
title: "Sumo odds (scraped from Marathonbet)"
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    navbar:
    - href: https://data.world/cervus/sumo-wrestling-betting-odds
      title: Data
    - href: https://github.com/Cervus1983
      title: Author
    source_code: embed
---


```{r}
library(flexdashboard)
library(plotly)
library(shiny)
library(stringr)
library(tidyverse)
```


```{r include=FALSE}
library(data.world)
set_config(cfg_env(auth_token_var = "DW_API_TOKEN"))

options(stringsAsFactors = FALSE)

# wrapper for data frame concatenation
dfapply <- function(...) do.call(rbind, lapply(...))

# downloads entire data set into single data frame
dataset_as_data_frame <- function(dataset_name) {
	dataset <- paste(Sys.getenv("DW_USER"), dataset_name, sep = "/")
	dfapply(
		map_chr(get_dataset(dataset)$files, "name"),
		function(file_name) download_file_as_data_frame(dataset, file_name)
	)
}

#load("all_odds.RData")
all_odds <- dataset_as_data_frame("sumo-wrestling-betting-odds") %>% 
	mutate(basho = substr(ts, 1, 7))
```


```{r}
# drop-down list of basho (tournaments)
output$basho_selector <- renderUI({
	selectInput(
		inputId = "basho",
		label = "Basho:",
		choices = all_odds %>% pull(basho) %>% unique() %>% rev()
	)
})
```


```{r}
# odds _changes_ for selected basho
odds <- reactive({
	req(input$basho)
	
	all_odds %>% 
		filter(basho == input$basho) %>% 
		group_by(rikishi1, rikishi2) %>% 
		arrange(ts) %>% 
		mutate(
			# get rid of extra decimals
			odds1 = round(odds1, 2),
			odds2 = round(odds2, 2),
			# deal with <date>T<time>Z format
			ts = ts %>% sub("T", " ", .) %>% sub("Z", "", .) %>% as.POSIXct(),
			# look for changes
			odds1_lag = lag(odds1),
			odds1_lead = lead(odds1),
			odds2_lag = lag(odds2),
			odds2_lead = lead(odds2)
		) %>% 
		ungroup() %>% 
		filter(is.na(odds1_lag) | is.na(odds2_lag) | is.na(odds1_lead) | is.na(odds2_lead) | odds1 != odds1_lag | odds2 != odds2_lag) %>% 
		select(rikishi1, odds1, rikishi2, odds2, ts)
})
```


```{r}
# checkboxes for rikishi (wrestlers)
output$rikishi_selector <- renderUI({
	req(odds())
	
	list(
		br(),
		selectInput(
			inputId = "rikishi",
			label = "Rikishi:",
			choices = c(odds()$rikishi1, odds()$rikishi2) %>% unique() %>% sort(),
			# top dog is selected initially
			selected = odds() %>% 
				transmute(
					favourite = ifelse(odds1 < odds2, rikishi1, rikishi2),
					odds = ifelse(odds1 < odds2, odds1, odds2)
				) %>% 
				group_by(favourite) %>% 
				summarise(mean(odds)) %>% 
				arrange(`mean(odds)`) %>% 
				.$favourite %>% 
				head(1)
		),
		br()
	)
})
```


```{r}
# finally, the plot
output$plot <- renderPlotly({
	req(length(input$rikishi) > 0)

	odds() %>% 
		group_by(rikishi1, rikishi2) %>% 
		filter(rikishi1 %in% input$rikishi | rikishi2 %in% input$rikishi) %>% 
		plot_ly(
			color = ~paste0(rikishi1, "-", rikishi2),
			colors = "Paired",
			x = ~as.POSIXct(ts)
		) %>% 
		add_trace(
			hoverinfo = "text",
			line = list(shape = "hv", width = 1),
			mode = "lines+markers",
			marker = list(size = 3),
			text = ~sprintf("<b>%.4g %s</b> %s %s", odds1, rikishi1, rikishi2, format(ts, "%Y-%m-%d %H:%M")),
			type = "scatter",
			y = ~odds1
		) %>% 
		add_trace(
			hoverinfo = "text",
			line = list(shape = "hv", width = 1),
			marker = list(size = 3),
			mode = "lines+markers",
			text = ~sprintf("<b>%.4g %s</b> %s %s", odds2, rikishi2, rikishi1, format(ts, "%Y-%m-%d %H:%M")),
			type = "scatter",
			y = ~odds2
		) %>% 
		layout(
			hovermode = "x",
			showlegend = FALSE,
			xaxis = list(
				title = ""
			),
			yaxis = list(
				dtick = 1,
				rangemode = "tozero",
				title = ""
			)
		) %>% 
		config(
			collaborate = FALSE,
			displaylogo = FALSE,
			modeBarButtonsToRemove = c(
				"autoScale2d",
				"hoverClosestCartesian",
				"hoverCompareCartesian",
				"lasso2d",
				"select2d",
				"toggleSpikelines",
				"zoomIn2d",
				"zoomOut2d"
			)
		)
})
```


Column {.sidebar}
-----------------------------------------------------------------------

```{r}
uiOutput("basho_selector")
uiOutput("rikishi_selector")
```


Column
-----------------------------------------------------------------------

```{r}
plotlyOutput("plot", height = "100%")
```
